config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top"

  devise_for :user, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # ゲストログイン用です
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # 管理者については登録済のため[新規登録・パスワード変更]のpathを使えないようにしています。
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    resources :bands, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resource :band_permits, only: [:create, :destroy]
      resource :band_members, only: [:create, :destroy]
    end
    # バンドに参加申請をしているユーザー一覧を表示するため
    get "bands/:id/band_permits" => "bands#band_permits", as: :band_permit

    resources :messages, only: [:create]
    resources :dm_rooms, only: [:create, :index, :show, :edit, :update, :destroy]
    get "dm_rooms/new/:id" => "dm_rooms#new", as: "new_dm_room"
    post "entry" => "dm_rooms#room_add_user"
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorite, only: [:create, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :update] do
      member do #user.idが必要なためmemberを使用しています。
        get :bookmarks #ブックマーク登録した投稿を一覧で表示するアクションです
      end
    end
    get "search" => "searches#search"
    get "tagsearches/search" => "tagsearches#tagsearch"
  end

  get "admin" => "admin/homes#top"
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :motivations, only: [:index, :create, :edit, :update]
    resources :musical_instruments, only: [:index, :create, :edit, :update]
    resources :users, only: [:show, :update]
    resources :bands, only: [:index, :show, :update]
    resources :posts, only: [:index, :destroy]
    resources :post_comments, only: [:index, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord

  validates :name, presence: true

  belongs_to :owner, class_name: "User"
  belongs_to :genre
  has_many :band_members, dependent: :destroy
  has_many :band_permits, dependent: :destroy
  has_many :users, through: :band_members

  has_one_attached :band_image


  def is_owned_by?(user)
    owner.id == user.id
  end

  def include_user?(user)
    band_members.exists?(user_id: user.id)
  end

  def get_band_image
    (band_image.attached?) ? band_image: 'no_image.jpg'
  end

  def self.looks(search, word)
    if search == "partial_match"
      @band = Band.where("name LIKE?", "%#{word}%")
    else
      Band.all
    end
  end

  paginates_per 10

end

app/models/band_member.rb
class BandMember < ApplicationRecord
  belongs_to :user
  belongs_to :band
end

app/models/band_permit.rb
class BandPermit < ApplicationRecord
  
  belongs_to :user
  belongs_to :band
  
end

app/models/dm_room.rb
class DmRoom < ApplicationRecord

  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  
end

app/models/entry.rb
class Entry < ApplicationRecord
  
  belongs_to :user
  belongs_to :dm_room
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :bands, dependent: :destroy
  
  validates :name, presence: true
  
end

app/models/message.rb
class Message < ApplicationRecord
  
  belongs_to :user
  belongs_to :dm_room
  
  validates :content, presence: true
end

app/models/motivation.rb
class Motivation < ApplicationRecord
  
  has_many :users
  
  validates :name, presence: true

end

app/models/musical_instrument.rb
class MusicalInstrument < ApplicationRecord
  
  has_many :users
  
  validates :name, presence: true

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :body, presence: true

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.looks(search, word)
    if search == "partial_match"
      @post = Post.where("body LIKE?", "%#{word}%")
    else
      @post = Post.all
    end
  end

  paginates_per 10


end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
  validates :comment, presence: true
  
  paginates_per 10

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  
  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  
  belongs_to :musical_instrument
  belongs_to :motivation
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :band_members, dependent: :destroy
  has_many :band_permits, dependent: :destroy
  has_many :bands, through: :band_members
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :dm_rooms, through: :entries

  has_one_attached :profile_image


  def get_profile_image
    (profile_image.attached?) ? profile_image: "no_image.jpg"
  end

  def self.guest
    find_or_create_by!(email: "guest@guest") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guest"
      user.musical_instrument_id = 1
      user.motivation_id = 1
      user.introduction = "ゲストです"
    end
  end

  def self.looks(search, word)
    if search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end

  paginates_per 10

end

app/controllers/admin/bands_controller.rb
class Admin::BandsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @bands = Band.order("id DESC").page(params[:page]).per(7)
  end

  def show
    @band = Band.find(params[:id])
  end

  def update #素行の悪いバンドを取り締まるため、問題アリと表示させることができます、取り消しも可能
    @band = Band.find(params[:id])
    @band.update(band_params)
    flash[:notice] = "バンドの情報を更新しました"
    redirect_to request.referer
  end
  
  private
  
  def band_params
    params.require(:band).permit(:band_status2)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when User
      root_path
    else
      root_path
    end 
  end
end

app/helpers/admin/bands_helper.rb
module Admin::BandsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musical_instruments_helper.rb
module MusicalInstrumentsHelper
end

app/views/admin/bands/index.html.erb
<h3 class="my-3">バンド一覧</h3>
<table class="table">
  <thead style="background-color: #474343; color: white;">
    <tr>
      <th>画像</th>
      <th>バンド名</th>
      <th>メンバー数</th>
      <th>募集の有無</th>
      <th>評判</th>
    </tr>
  </thead>
  <tbody>
    <% @bands.each do |band| %>
    <tr class="list">
      <td><%= image_tag band.get_band_image, size: "50x50" %></td>
      <td><%= link_to band.name, admin_band_path(band.id) %></td>
      <td><%= band.users.count %></td>
    <% if band.band_status == true %>
      <td class="text-primary font-weight-bold">募集中</td>
    <% else %>
      <td class="text-secondary font-weight-bold">締切</td>
    <% end %>
    <% if band.band_status2 == true %>
      <td class="text-success font-weight-bold">正常</td>
    <% else %>
      <td class="text-danger font-weight-bold">問題あり</td>
    <% end %>
    </tr>
    <% end %>
  </tbody>
</table>
<style>
  .list:hover {
    background-color: #FFEFC9;
    box-shadow: 0 2px 4px rgba(0,0,0,0.5);
  }
  .item_paginate {
    display: flex;
    justify-content: center;
    align-items: center;
    width: 100%;
  }
  .pagination {
    text-align: center;
    width: 50px;
    font-size: 20px;
  }
  .pagination span {
    text-align: center;
    width: 50px;
    font-size: 20px;
  }
  .pagination a {
    color: #818181;
    display: block;
    width: 100%;
    height: 100%;
    padding: 10px;
  }
  .pagination a:hover{
    width: 50px;
    height: 50px;
    background-color: #474343;
    color: #FFF;
    border-radius: 100%;
    padding: 10px;
  }
  .current{
    font-weight: bold;
    color: #474343;
    padding: 10px;
  }
</style>

app/views/admin/bands/show.html.erb
<div class="row">
  <div class="col-md-3">
    <%= render "public/bands/info", band: @band %>
  </div>
  <div class="col-md-8 offset-md-1">
    <div class="row my-3" style="display: flex; align-items: center;">
      <%= form_with model: @band, url: admin_band_path(@band), method: :patch do |f| %>
        <div class="form-group p-2" style="background-color: #474343; color: white;">
          <%= f.label :status, "バンドステータス" %>　
          <%= f.radio_button :band_status2, "true" %><%= f.label :band_status2, '正常', value: true %>　
          <%= f.radio_button :band_status2, "false" %><%= f.label :band_status2, '問題アリ', value: false %>
          <%= f.submit "Save", data: {confirm: "ステータスを更新します"}, class: "btn btn-success" %>
        </div>
      <% end %>
      <% if @band.band_status2 == false %>
        <p class="text-danger ml-auto"><i class="fa-solid fa-triangle-exclamation"></i>問題アリ<i class="fa-solid fa-triangle-exclamation"></i></p>
      <% end %>
    </div>
    <h5>Band Member's</h5>
    <table class="table">
      <thead style="background-color: #474343; color: white;">
        <tr>
          <th>image</th>
          <th>name</th>
        </tr>
      </thead>
      <tbody>
        <% @band.users.each do |user| %>
        <tr class="list">
          <td><%= image_tag user.get_profile_image, size: "50x50" %></td>
          <td><%= link_to user.name, admin_user_path(user.id) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<style>
  .list:hover {
    background-color: #FFEFC9;
    box-shadow: 0 2px 4px rgba(0,0,0,0.5);
  }
</style>