config/routes.rb
Rails.application.routes.draw do

  root to: "public/homes#top"

  devise_for :user, controllers: {
    registrations: "public/registrations",
    sessions: "public/sessions"
  }
  # ゲストログイン用です
  devise_scope :user do
    post "users/guest_sign_in", to: "public/sessions#guest_sign_in"
  end

  # 管理者については登録済のため[新規登録・パスワード変更]のpathを使えないようにしています。
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  scope module: :public do
    resources :bands, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resource :band_permits, only: [:create, :destroy]
      resource :band_members, only: [:create, :destroy]
    end
    # バンドに参加申請をしているユーザー一覧を表示するため
    get "bands/:id/band_permits" => "bands#band_permits", as: :band_permit

    resources :messages, only: [:create]
    resources :dm_rooms, only: [:create, :index, :show, :edit, :update, :destroy]
    get "dm_rooms/new/:id" => "dm_rooms#new", as: "new_dm_room"
    post "entry" => "dm_rooms#room_add_user"
    resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
      resources :post_comments, only: [:create, :destroy]
      resource :favorite, only: [:create, :destroy]
    end
    resources :users, only: [:index, :show, :edit, :update] do
      member do #user.idが必要なためmemberを使用しています。
        get :bookmarks #ブックマーク登録した投稿を一覧で表示するアクションです
      end
    end
    get "search" => "searches#search"
    get "tagsearches/search" => "tagsearches#tagsearch"
  end

  get "admin" => "admin/homes#top"
  namespace :admin do
    resources :genres, only: [:index, :create, :edit, :update]
    resources :motivations, only: [:index, :create, :edit, :update]
    resources :musical_instruments, only: [:index, :create, :edit, :update]
    resources :users, only: [:show, :update]
    resources :bands, only: [:index, :show, :update]
    resources :posts, only: [:index, :destroy]
    resources :post_comments, only: [:index, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/band.rb
class Band < ApplicationRecord

  validates :name, presence: true

  belongs_to :owner, class_name: "User"
  belongs_to :genre
  has_many :band_members, dependent: :destroy
  has_many :band_permits, dependent: :destroy
  has_many :users, through: :band_members

  has_one_attached :band_image


  def is_owned_by?(user)
    owner.id == user.id
  end

  def include_user?(user)
    band_members.exists?(user_id: user.id)
  end

  def get_band_image
    (band_image.attached?) ? band_image: 'no_image.jpg'
  end

  def self.looks(search, word)
    if search == "partial_match"
      @band = Band.where("name LIKE?", "%#{word}%")
    else
      Band.all
    end
  end

  paginates_per 10

end

app/models/band_member.rb
class BandMember < ApplicationRecord
  belongs_to :user
  belongs_to :band
end

app/models/band_permit.rb
class BandPermit < ApplicationRecord
  
  belongs_to :user
  belongs_to :band
  
end

app/models/dm_room.rb
class DmRoom < ApplicationRecord

  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  
end

app/models/entry.rb
class Entry < ApplicationRecord
  
  belongs_to :user
  belongs_to :dm_room
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :bands, dependent: :destroy
  
  validates :name, presence: true
  
end

app/models/message.rb
class Message < ApplicationRecord
  
  belongs_to :user
  belongs_to :dm_room
  
  validates :content, presence: true
end

app/models/motivation.rb
class Motivation < ApplicationRecord
  
  has_many :users
  
  validates :name, presence: true

end

app/models/musical_instrument.rb
class MusicalInstrument < ApplicationRecord
  
  has_many :users
  
  validates :name, presence: true

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :body, presence: true

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def self.looks(search, word)
    if search == "partial_match"
      @post = Post.where("body LIKE?", "%#{word}%")
    else
      @post = Post.all
    end
  end

  paginates_per 10


end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
  validates :comment, presence: true
  
  paginates_per 10

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable
  
  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  
  belongs_to :musical_instrument
  belongs_to :motivation
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :band_members, dependent: :destroy
  has_many :band_permits, dependent: :destroy
  has_many :bands, through: :band_members
  has_many :entries, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :dm_rooms, through: :entries

  has_one_attached :profile_image


  def get_profile_image
    (profile_image.attached?) ? profile_image: "no_image.jpg"
  end

  def self.guest
    find_or_create_by!(email: "guest@guest") do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "guest"
      user.musical_instrument_id = 1
      user.motivation_id = 1
      user.introduction = "ゲストです"
    end
  end

  def self.looks(search, word)
    if search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end

  paginates_per 10

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path
    when User
      root_path
    else
      root_path
    end 
  end
end

app/helpers/admin/bands_helper.rb
module Admin::BandsHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musical_instruments_helper.rb
module MusicalInstrumentsHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_admin_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #474343; ">
    <div class="container">
      <a class="navbar-brand" href="/admin"><%= image_tag("logo.png", width: 100, height: 70) %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <p class="text-light ml-3 mt-3">Log In Administrator</p>
          <li class="nav-item">
          <%= link_to admin_posts_path, class: 'nav-link' do %>
            <button type="button" class="btn btn-outline-light"><i class="fa-solid fa-pen"></i><br>Posts</button>
          <% end %>
          </li>
          <li class="nav-item">
          <%= link_to admin_post_comments_path, class: 'nav-link' do %>
            <button type="button" class="btn btn-outline-light"><i class="fa-regular fa-comment-dots"></i><br>Comments</button>
          <% end %>
          </li>
          <li class="nav-item">
          <%= link_to admin_path, class: 'nav-link' do %>
            <button type="button" class="btn btn-outline-light"><i class="fa-solid fa-users"></i><br> Users</button>
          <% end %>
          </li>
          <li class="nav-item">
          <%= link_to admin_bands_path, class: 'nav-link' do %>
            <button type="button" class="btn btn-outline-light"><i class="fa-solid fa-music"></i><br> Bands</button>
          <% end %>
          </li>
          <li class="nav-item">
          <%= link_to admin_genres_path, class: 'nav-link' do %>
            <button type="button" class="btn btn-outline-light"><i class="fa-solid fa-list-ul"></i><br> Genres</button>
          <% end %>
          <li class="nav-item">
          <%= link_to admin_motivations_path, class: 'nav-link' do %>
            <button type="button" class="btn btn-outline-light"><i class="fa-solid fa-list-ul"></i><br> Motivations</button>
          <% end %>
          <li class="nav-item">
          <%= link_to admin_musical_instruments_path, class: 'nav-link' do %>
            <button type="button" class="btn btn-outline-light"><i class="fa-solid fa-list-ul"></i><br> Musical Instruments</button>
          <% end %>
          </li>
          <li class="nav-item">
          <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link' do %>
            <button type="button" class="btn btn-outline-light"><i class="fa-solid fa-right-from-bracket"></i><br> Log Out</button>
          <% end %>
          </li>
        <% else %>
          <li class="nav-item">
          <%= link_to posts_path, class: 'nav-link' do %>
            <button type="button" class="btn btn-outline-light"><i class="fa-solid fa-pen"></i> Posts</button>
          <% end %>
          </li>
          <li class="nav-item">
          <%= link_to bands_path, class: 'nav-link' do %>
            <button type="button" class="btn btn-outline-light"><i class="fa-solid fa-music"></i> Bands</button>
          <% end %>
          </li>
          <li class="nav-item">
          <%= link_to new_user_registration_path, class: 'nav-link' do %>
            <button type="button" class="btn btn-outline-light"><i class="fa-solid fa-user-plus"></i> Sign Up</button>
          <% end %>
          </li>
          <li class="nav-item">
          <%= link_to user_session_path, class: 'nav-link' do %>
            <button type="button" class="btn btn-outline-light"><i class="fa-solid fa-right-to-bracket"></i> Log In</button>
          <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>
<style>
  .navbar-brand:hover {
    box-shadow: 0 3px 5px rgba(0,0,0,1);
  }
</style>

app/views/layouts/_footer.html.erb
<footer>
  <div class="fixed-bottom text-white" style="background-color: #474343; ">
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          Band_Connect@DMM WEBCAMP
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_public_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #474343; ">
    <div class="container">
      <a class="navbar-brand" href="/"><%= image_tag("logo.png", width: 100, height: 70) %></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
          <div class="mt-3 mr-5 pr-5" style="color: white;">
            Welcome！<%= current_user.name %>！
          </div>
          <li class="nav-item">
          <%= link_to user_path(current_user.id), class: 'nav-link' do %>
            <button type="button" class="btn btn-outline-light"><i class="fa-solid fa-user"></i> My Page</button>
          <% end %>
          </li>
          <li class="nav-item">
          <%= link_to posts_path, class: 'nav-link' do %>
            <button type="button" class="btn btn-outline-light"><i class="fa-solid fa-pen"></i> Posts</button>
          <% end %>
          </li>
          <li class="nav-item">
          <%= link_to users_path, class: 'nav-link' do %>
            <button type="button" class="btn btn-outline-light"><i class="fa-solid fa-users"></i> Users</button>
          <% end %>
          </li>
          <li class="nav-item">
          <%= link_to bands_path, class: 'nav-link' do %>
            <button type="button" class="btn btn-outline-light"><i class="fa-solid fa-music"></i> Bands</button>
          <% end %>
          </li>
          <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link' do %>
            <button type="button" class="btn btn-outline-light"><i class="fa-solid fa-right-from-bracket"></i> Log Out</button>
          <% end %>
          </li>
        <% else %>
          <li class="nav-item">
          <%= link_to posts_path, class: 'nav-link' do %>
            <button type="button" class="btn btn-outline-light"><i class="fa-solid fa-pen"></i> Posts</button>
          <% end %>
          </li>
          <li class="nav-item">
          <%= link_to bands_path, class: 'nav-link' do %>
            <button type="button" class="btn btn-outline-light"><i class="fa-solid fa-music"></i> Bands</button>
          <% end %>
          </li>
          <li class="nav-item">
          <%= link_to new_user_registration_path, class: 'nav-link' do %>
            <button type="button" class="btn btn-outline-light"><i class="fa-solid fa-user-plus"></i> Sign Up</button>
          <% end %>
          </li>
          <li class="nav-item">
          <%= link_to user_session_path, class: 'nav-link' do %>
            <button type="button" class="btn btn-outline-light"><i class="fa-solid fa-right-to-bracket"></i> Log In</button>
          <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  <% if user_signed_in? %>
    <%= render "public/searches/window" %>
  <% end %>
  </nav>
</header>
<style>
  .navbar-brand:hover {
    box-shadow: 0 2px 4px rgba(0,0,0,0.5);
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bandconnect</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/41df1fbdb3.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
      body {
        background-color: #F7F1E1;
      }
      main {
        margin-bottom: 60px;
        padding-top: 5px;
        padding-bottom: 10px;
      }
      .flash-message {
        border-radius: 5px;
        padding: 16px 24px;
        margin: 16px 0px;
      }
       
      .flash-message.notice {
        background-color: #bcdfff;
        color: #0067C0;
        border: solid 1px #0067C0;
      }
       
      .flash-message.alert {
        background-color: #ffd4d1;
        color: #930403;
        border: solid 1px #930403;
      }
      .field_with_errors {
        display: contents;
      }
    </style>
  </head>

  <body>
    <% if request.fullpath.include? "/admin" %>
      <%= render "layouts/admin_header" %>
    <% else %>
      <%= render "layouts/public_header" %>
    <% end %>
    <main>
      <div class="container">
        <% flash.each do |message_type, message| %>
          <div class="flash-message <%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
      </div>
    </main>
    <%= render "layouts/footer" %>
  </body>
</html>